### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by SleepProgger** [ghaerr/agg-2.6#4]
First of all: thanks for maintaining (?) a version of this awesome library,

Just to be sure tho: Since this work is based on the 2.4 version it is licensed under a BSD License, right ?
If so, is there any way to make this a bit more clear in this repository by any chance ?

**Comment by ghaerr** [comment]
Hello @SleepProgger,

This repo was cloned with history on May 26, 1019 from the official Sourceforge repository after v2.6 was created. It is my understanding that v2.6 is based on a branch from the final 2.4 code, done explicitly with no other changes, to avoid the change of license requirement (GPL) Maxim introduced in v2.5. I added a couple of directories and source/Makefiles to additionally support the Microwindows/Nano-X platform, and allow building all the demos without the AGG website up. Nothing else has changed.

I would like to check a few file histories to confirm this, as it seems that Maxim never kept a LICENSE file itself in the source code, only on the web site. I have copies of almost all pages of the (now-defunct) website, and would like to research a bit more to make sure this is correct for the files in this repo. I'll try to do that shortly.

Thank you!

**Comment by ghaerr** [comment]
Hello @SleepProgger,

I've updated README.md to clarify the licensing details of AGG 2.6.

Thank you!
